@startuml TocarInstrumentos
participant Banda order 10
participant Musico order 20
participant Instrumento order 30
skinparam style strictuml
Banda->Musico++: 1:tocar()
Musico->Instrumento++: 2:SerTocado()

@enduml